# Generated by Django 5.1.5 on 2025-02-08 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklendings',
            name='date',
        ),
        migrations.AddField(
            model_name='booklendings',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 22, 24, 14, 675880)),
        ),
    ]
