# Generated by Django 5.1.5 on 2025-02-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookPlatform', '0002_books_is_lended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='is_lended',
            new_name='is_listed',
        ),
    ]
