# Generated by Django 5.1.5 on 2025-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPlatform', '0003_rename_is_lended_books_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_avaliable',
            field=models.BooleanField(default=False),
        ),
    ]
